version: '3.9'
services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo:/data/mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    hostname: mongo
volumes:
  mongo: